[package]
name = "nesulator"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "crates/*",
]

[dependencies]
m6502 = { path = "./crates/m6502" }
crossterm = "0.23"
nom = "7.1.1"
